name: projects
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.5
  video_player: ^2.8.2

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.0

  # ✅ Firebase 최신 규칙에 맞는 조합
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0

  google_maps_flutter: ^2.5.0
  flutter_naver_map: ^1.4.1+1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.2.2
  xml: ^6.5.0

  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sound/
    - assets/audio/
    - assets/image/
    - .env
